version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: "yarn start"
    env_file: .env
    volumes:
      - ./app:/app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"